#=========================================================================
# TravisCI Setup
#=========================================================================

#------------------------------------------------------------------------
# language and build matrix
#------------------------------------------------------------------------

dist: xenial
language: python

python:
 - "3.7"

env:
 - CONFIG="-v --tb=short --cov=./ --cov-report xml"

#------------------------------------------------------------------------
# install dependencies
#------------------------------------------------------------------------

install:

 # Install packages
 - sudo apt-get install -y graphviz

 # Install verilator
 - wget https://github.com/pymtl/verilator-travisci-cache/raw/master/verilator-travis-4.036.tar.gz
 - tar -C ${HOME} -xzf verilator-travis-4.036.tar.gz
 - export VERILATOR_ROOT=${HOME}/verilator
 - export PATH=${VERILATOR_ROOT}/bin:${PATH}
 - export PYMTL_VERILATOR_INCLUDE_DIR=${VERILATOR_ROOT}/share/verilator/include
 - verilator --version

 # Install PyMTL3
 - pip install git+https://github.com/tancheng/pymtl3.git
 - pip install hypothesis
 - pip install codecov
 - pip install pytest-cov
 - pip list

#------------------------------------------------------------------------
# test runner
#------------------------------------------------------------------------

script:
 - py.test ../ $CONFIG

#-------------------------------------------------------------------------
# after success
#-------------------------------------------------------------------------

after_success:
 - codecov 
 - bash <(curl -s https://codecov.io/bash)
